import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React from "react";
import Gallery from '@/pages/Gallery';

export default function Home() {
  
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);
  
  return (
    domLoaded && 
    <>
      <Head>
        <title>El bisne</title>
        <meta name="description" content="Generated by create next app by Frank Pérez Fleita" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <React.StrictMode>
          <main className={styles.main}>
            <Gallery />
          </main>
      </React.StrictMode>
    </>
  )
}
