import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Menu from '@/components/Menu'
import Search from './Search'
import Gallery from './Gallery'
import { useState } from "react";
import { Routes, BrowserRouter as Router, Route } from 'react-router-dom'
import { ContextProvider } from '@/context/Context'


export default function Home() {
  
  const[menu, setMenu] = useState(false);
  
  return (
    <>
      <Head>
        <title>El bisne</title>
        <meta name="description" content="Generated by create next app by Frank Pérez Fleita" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ContextProvider>
        <Router>
            <main className={styles.main}>
            <Menu/>
            <Routes>
              <Route exact path='/' element={<Gallery />}/>
              <Route exact path='/Search' element={<Search/>} />
            </Routes>
            </main>
        </Router>
      </ContextProvider>
    </>
  )
}
